export const APPROVAL_ERROR_DISMISS_MS = 5_000;

export const MARGIN_MODE_SUCCESS_DURATION_MS = 1_000;
export const SWAP_SUCCESS_DURATION_MS = 1_500;

export const ORDER_TOAST_SUCCESS_DURATION_MS = 5_000;

export const CHART_ALL_MIDS_TTL_MS = 10_000;
